### ISSUE TITLE
Adblock Plus - Video skip after ad bypass

### ISSUE THREAD

**Issue by Jayjayjay32** [crazyrabbit0/UserScripts#2]
If this script is used in tandem with Adblock Plus, when an ad is blocked by the adblocker before a song in a playlist, that song would be skipped entirely.

I recommend anyone with both this script and Adblock Plus to get a different adblocker for YouTube, as that would solve this issue; of course still using Adblock Plus for other websites won't be problematic.

**Comment by crazyrabbit0** [comment]
Interesting, thanks for letting me know 🙏
When I have free time, I'll check if it's fixable 🤔

**Comment by crazyrabbit0** [comment]
So, I did check for the bug, but couldn't reproduce it, which browser are you using ?

**Comment by Jayjayjay32** [comment]
I was using Chrome, maybe it was because I had a lot of tabs open at the time?

**Comment by Jayjayjay32** [comment]
I was using Chrome, maybe it was because I had a lot of tabs open at the time?

Also, sorry for mis-pressing the close button, I suppose I hadn't posted comments on this site in a while, my bad

**Comment by crazyrabbit0** [comment]
> Also, sorry for mis-pressing the close button, I suppose I hadn't posted comments on this site in a while, my bad

Don't worry 😅

Does it happen only when a lot of tabs are open ?

Do you, by any chance, have the "Memory Saver" option turned on ?

![Memory Saver](https://github.com/crazyrabbit0/UserScripts/assets/5244848/af672adb-0ecc-407b-a4d5-9cdfcae3aa86)

**Comment by Jayjayjay32** [comment]
Very sorry for the late response, I do both have a lot of tabs and memory saver on, however I checked and the same thing happens with memory saver off and with only one tab open, so there might be something entirely different that's making it hard to reproduce.

This isn't the biggest issue since a way of getting around it is known, so don't fret too much over this. I'll still be willing to help if you have any other questions about what makes my situation different from yours.

**Comment by crazyrabbit0** [comment]
Could you try [this test](https://github.com/crazyrabbit0/UserScripts/raw/testing/YouTube%20Playlist%20AutoPlay.user.js) that I made and let me know if it works ?

**Comment by Jayjayjay32** [comment]
I'm writing now just to say that I'm terribly sorry I essentially ghosted you; I should've found the time to at least somewhat respond to your message and I just didn't, I really should've done better.

If you're still concerned about the issue, it seems to be completely fixed on my end, so you don't have to worry about that.

I still feel I need to apologize for not giving a response so long; sure, I've been busy for quite a bit, yet I know I can't use that as an excuse because I should've just told you I was busy earlier instead of just, saying nothing, at all; I'm very sorry for bringing you through this and I hope nobody else does this to you in the future.

**Comment by crazyrabbit0** [comment]
Your apology is appreciated 🙏

I guess the issue was fixed with one of the later releases.
