### ISSUE TITLE
Playlist lock - Always goes to next video when choosing any video

### ISSUE THREAD

**Issue by JeffreyMercado** [crazyrabbit0/UserScripts#4]
This stems from my testing in #3.

If you try to navigate to a different video within the playlist, it seems the script overrides the selection and causes the previous "next video" in the list to be opened instead.

Repro:
1. Start playing a playlist (also refresh browser after starting)
2. In the playlist panel, choose any video other than the next video (e.g., If started on video 1, choose video 3)
3. Youtube navigates to the old "next video" instead (i.e., Navigates to video 2 in previous example)

**Comment by JeffreyMercado** [comment]
Actually, seems worse than I initially thought. It seems to override _anything_ that would navigate away from the video.

* Clicking on any video listed in the side panels will jump to the "next video" in the playlist.
* Even affects using the browser back button, could potentially get into a redirect loop and stuck on the same video.

**Comment by crazyrabbit0** [comment]
That was a weird one _(sadly YouTube doesn't have distinct classes for videos that don't load)_.
The latest version should fix this issue _(but the blank buffering problem is no longer supported)_.

**Comment by JeffreyMercado** [comment]
This bug popped up again, I think I found a trigger or related case.

If playing a playlist and switching to the editor page for that playlist. Delete an earlier video from the current position (or maybe move another video before the current position). Doing so updates the playlist both what YT recognizes and what's currently playing. The script will lose track of the next video and think the current video is the next. After that, it seems to be in an infinite loop playing the same video over and over. I suspect it would do the same if you tried to choose any other video not in the playlist, it will just go back to the old "current" video.

**Comment by crazyrabbit0** [comment]
I tried this but couldn't replicate the faulty behavior, could you record what you are doing so I can have a full picture ?
