### ISSUE TITLE
Auto-check discretion warnings

### ISSUE THREAD

**Issue by JeffreyMercado** [crazyrabbit0/UserScripts#6]
Had this video in a playlist, when I tried to watch the video by clicking on the "I understand and wish to proceed," ~it moves to the next video in the playlist.~

https://youtu.be/gbsqL-2NMEs

~It should play the video instead of moving on to the next in the playlist.~ (couldn't repro)

Could the script automatically play the video, despite the warning? Or maybe make it an option somehow? I don't want playback to stop for anything, not even this.

**Comment by crazyrabbit0** [comment]
I don't intend on making this feature.
These warnings MUST be displayed, someone might accidentally click on such a video.
